tap "homebrew/bundle"
tap "homebrew/services"
tap "railwaycat/emacsmacport"
brew "glib"
brew "gmp"
brew "openssl@3"
brew "gnutls"
brew "emacs", restart_service: :changed
brew "eza"
brew "fd"
brew "fzf"
brew "gcc"
brew "git"
brew "harfbuzz"
brew "hugo"
brew "jansson"
brew "libgccjit"
brew "librsvg"
brew "libyaml"
brew "neovim"
brew "node"
brew "openjdk"
brew "pipx"
brew "pyenv"
brew "python@3.10"
brew "python@3.12"
brew "ripgrep"
brew "rust"
brew "stow"
brew "tree"
brew "tree-sitter"
brew "uv"
brew "zoxide"
cask "1password", args: { appdir: "/Applications" }
cask "adobe-creative-cloud", args: { appdir: "/Applications" }
cask "coteditor", args: { appdir: "/Applications" }
cask "cursor"
cask "docker-desktop", args: { appdir: "/Applications" }
cask "google-chrome", args: { appdir: "/Applications" }
cask "google-drive", args: { appdir: "/Applications" }
cask "intellij-idea", args: { appdir: "/Applications" }
cask "iterm2", args: { appdir: "/Applications" }
cask "jetbrains-toolbox", args: { appdir: "/Applications" }
cask "microsoft-outlook"
cask "postman", args: { appdir: "/Applications" }
cask "pycharm", args: { appdir: "/Applications" }
cask "slack", args: { appdir: "/Applications" }
cask "spotify", args: { appdir: "/Applications" }
cask "visual-studio-code", args: { appdir: "/Applications" }
cask "wezterm"
cask "zoom", args: { appdir: "/Applications" }
vscode "8amjp.charactercount"
vscode "alefragnani.bookmarks"
vscode "amazonwebservices.aws-toolkit-vscode"
vscode "batisteo.vscode-django"
vscode "bradlc.vscode-tailwindcss"
vscode "csstools.postcss"
vscode "danields761.dracula-theme-from-intellij-pythoned"
vscode "dannysteenman.cloudformation-yaml-snippets"
vscode "davidanson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "docker.docker"
vscode "donjayamanne.python-environment-manager"
vscode "donjayamanne.python-extension-pack"
vscode "editorconfig.editorconfig"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.dotnet-test-explorer"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.github-vscode-theme"
vscode "ics.japanese-proofreading"
vscode "jamesmaj.easy-icons"
vscode "kevinrose.vsc-python-indent"
vscode "magicstack.magicpython"
vscode "mgmcdermott.vscode-language-babel"
vscode "ms-azure-load-testing.microsoft-testing"
vscode "ms-azuretools.azure-dev"
vscode "ms-azuretools.vscode-azureappservice"
vscode "ms-azuretools.vscode-azurecontainerapps"
vscode "ms-azuretools.vscode-azurefunctions"
vscode "ms-azuretools.vscode-azureresourcegroups"
vscode "ms-azuretools.vscode-azurestaticwebapps"
vscode "ms-azuretools.vscode-azurevirtualmachines"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-cosmosdb"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-dotnettools.csdevkit"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-kubernetes-tools.vscode-kubernetes-tools"
vscode "ms-python.autopep8"
vscode "ms-python.black-formatter"
vscode "ms-python.debugpy"
vscode "ms-python.flake8"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.vscode-node-azure-pack"
vscode "ms-vscode.vscode-typescript-next"
vscode "ms-windows-ai-studio.windows-ai-studio"
vscode "njpwerner.autodocstring"
vscode "openai.chatgpt"
vscode "oxc.oxc-vscode"
vscode "pkief.material-icon-theme"
vscode "pmcxs.vscode-mindmap"
vscode "rdebugger.r-debugger"
vscode "redhat.vscode-xml"
vscode "redhat.vscode-yaml"
vscode "reditorsupport.r"
vscode "reditorsupport.r-syntax"
vscode "teamsdevapp.vscode-ai-foundry"
vscode "visualstudioexptteam.intellicode-api-usage-examples"
vscode "visualstudioexptteam.vscodeintellicode"
vscode "vue.volar"
vscode "wholroyd.jinja"
vscode "yzhang.markdown-all-in-one"
